language: go

dist: xenial

notifications:
  email: true

go:
- 1.12.x

env:
  global:
  - GO111MODULE=on

before_install:
- sudo apt-get update
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x
- openssl aes-256-cbc -K $encrypted_9d748cee9f61_key -iv $encrypted_9d748cee9f61_iv -in vpc.env.enc -out vpc.env -d

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
- cd vpcclassicv1 && go test -run TestVpcClassicV1 && go test `go list ./...` -v -tags=integration -skipForMockTesting -testCount && cd ..
- cd vpcv1 && go test -run TestVpcV1 && go test `go list ./...` -v -tags=integration -skipForMockTesting -testCount && cd ..
- golangci-lint run