language: go

dist: xenial

notifications:
  email: true

env:
  global:
  - GO111MODULE=on

before_install:
- sudo apt-get update
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
# - cd vpcclassicv1 && go test -run TestVpcClassicV1
# - go test `go list ./...` -v -tags=integration -skipForMockTesting -testCount && cd ..
# - cd vpcv1 && go test -run TestVpcV1
# - go test `go list ./...` -v -tags=integration -skipForMockTesting -testCount && cd ..
- golangci-lint run